import os
from datetime import datetime

TOOLS_DIR = "tools"
INDEX_FILE = "index.html"

def generate_index():
    files = sorted(os.listdir(TOOLS_DIR), reverse=True)
    links = []

    for file in files:
        if file.endswith(".html"):
            filepath = f"{TOOLS_DIR}/{file}"
            tool_name = file.replace(".html", "")
            links.append(f'<li><a href="{filepath}" target="_blank">{tool_name}</a></li>')

    html_content = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <title>🧠 Auto AI Tools - Daily Factory</title>
        <meta name="description" content="Explore AI-generated tools created daily. Fully automated and constantly evolving.">
        <style>
            body {{ font-family: sans-serif; background: #f8f9fa; padding: 30px; }}
            h1 {{ color: #333; }}
            ul {{ list-style-type: none; padding-left: 0; }}
            li {{ margin-bottom: 10px; }}
            a {{ color: #007bff; text-decoration: none; font-weight: bold; }}
            a:hover {{ text-decoration: underline; }}
        </style>
    </head>
    <body>
        <h1>🛠️ Daily Auto-Generated AI Tools</h1>
        <p>Updated: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}</p>
        <ul>
            {"".join(links)}
        </ul>
        <p style="margin-top:40px; font-size: 14px;">Auto-generated by AI Factory | No manual effort | Infinite AI growth</p>
    </body>
    </html>
    """

    with open(INDEX_FILE, "w", encoding="utf-8") as f:
        f.write(html_content)

generate_index()
